export const Images = {
    logo_mini: require('./logo-mini.svg').default,
    logo: require('./logo.svg').default,
    favicon: require('./favicon.png').default,

    locksreen_bg: require('./auth/lockscreen-bg.jpg'),
    login_bg: require('./auth/Login_bg.jpg'),
    login_bg2: require('./auth/Login_bg2.jpg'),
    login_bg1: require('./auth/login-bg.jpg'),
    register_bg: require('./auth/register-bg.jpg'),

    banner_1: require('./carousel/banner_1.jpg'),
    banner_2: require('./carousel/banner_2.jpg'),
    banner_3: require('./carousel/banner_3.jpg'),
    banner_4: require('./carousel/banner_4.jpg'),
    banner_5: require('./carousel/banner_5.jpg'),
    banner_6: require('./carousel/banner_6.jpg'),
    banner_7: require('./carousel/banner_7.jpg'),
    banner_8: require('./carousel/banner_8.jpg'),
    banner_9: require('./carousel/banner_9.jpg'),
    banner_10: require('./carousel/banner_10.jpg'),
    banner_11: require('./carousel/banner_11.jpg'),
    banner_12: require('./carousel/banner_12.jpg'),

    circle_png: require('./dashboard/circle.png'),
    circle_svg: require('./dashboard/circle.svg'),
    Group_123: require('./dashboard/Group126@2x.png'),
    Rectangle: require('./dashboard/Rectangle.jpg'),
    img_1: require('./dashboard/img_1.jpg'),
    img_2: require('./dashboard/img_2.jpg'),
    img_3: require('./dashboard/img_3.jpg'),
    img_4: require('./dashboard/img_4.jpg'),
    img_5: require('./dashboard/Img_5.jpg'),
    img_6: require('./dashboard/img_6.jpg'),

    face_1: require('./faces/face1.jpg'),
    face_2: require('./faces/face2.jpg'),
    face_3: require('./faces/face3.jpg'),
    face_4: require('./faces/face4.jpg'),
    face_5: require('./faces/face5.jpg'),
    face_6: require('./faces/face6.jpg'),
    face_7: require('./faces/face7.jpg'),
    face_8: require('./faces/face8.jpg'),
    face_9: require('./faces/face9.jpg'),
    face_10: require('./faces/face10.jpg'),
    face_11: require('./faces/face11.jpg'),
    face_12: require('./faces/face12.jpg'),
    face_13: require('./faces/face13.jpg'),
    face_14: require('./faces/face14.jpg'),
    face_15: require('./faces/face15.jpg'),
    face_16: require('./faces/face16.jpg'),
    face_17: require('./faces/face17.jpg'),
    face_18: require('./faces/face18.jpg'),
    face_19: require('./faces/face19.jpg'),
    face_20: require('./faces/face20.jpg'),
    face_21: require('./faces/face21.jpg'),
    face_22: require('./faces/face22.jpg'),
    face_23: require('./faces/face23.jpg'),
    face_24: require('./faces/face24.jpg'),
    face_25: require('./faces/face25.jpg'),
    face_26: require('./faces/face26.jpg'),
    face_27: require('./faces/face27.jpg'),

    pic_1: require('./faces-clipart/pic-1.png'),
    pic_2: require('./faces-clipart/pic-2.png'),
    pic_3: require('./faces-clipart/pic-3.png'),
    pic_4: require('./faces-clipart/pic-4.png'),
    pic_8: require('./faces-clipart/pic-8.png'),

    interface_1_001: require('./file-icons/64/001-interface-1.png'),
    tool_002: require('./file-icons/64/002-tool.png'),
    interface_003: require('./file-icons/64/003-interface.png'),
    folder_1_004: require('./file-icons/64/004-folder-1.png'),
    database_005: require('./file-icons/64/005-database.png'),
    record_006: require('./file-icons/64/006-record.png'),
    folder_007: require('./file-icons/64/007-folder.png'),
    archive_008: require('./file-icons/64/008-archive.png'),

    interface_1_128_001: require('./file-icons/128/001-interface-1.png'),
    tool_128_002: require('./file-icons/128/002-tool.png'),
    interface_128_003: require('./file-icons/128/003-interface.png'),
    folder_1_128_004: require('./file-icons/128/004-folder-1.png'),





}